env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:solid/typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - solid
rules:
  # https://typescript-eslint.io/rules/no-unused-vars/
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^_\\w*"
      vars: all
